version: "3.7"

services:
  # jupyterlab with pyspark
  base-notebook:
    #image: jupyter/base-notebook
    build: .
    env_file:
      - .env
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
